import './models/listings.dart';

List<Listing> listings = [
  Listing(
      id: "1",
      state: "Active",
      name: "Black Jacket",
      postDate: "Tues, 17 Nov",
      requests: 10,
      likes: 11,
      views: 100,
      imgURL: 'assets/images/jacket.jpg'),
  Listing(
      id: "2",
      state: "Shared",
      name: "Wooden chair",
      postDate: "Tues, 17 Nov",
      requests: 9,
      likes: 7,
      views: 19,
      imgURL: 'assets/images/chair.jpg'),
  Listing(
      id: "3",
      state: "Active",
      name: "Black Jacket",
      postDate: "Tues, 18 Nov",
      requests: 9,
      likes: 6,
      views: 100,
      imgURL: 'assets/images/jacket.jpg'),
  Listing(
      id: "4",
      state: "Shared",
      name: "Black Jacket",
      postDate: "Tues, 18 Nov",
      requests: 9,
      likes: 6,
      views: 100,
      imgURL: 'assets/images/jacket.jpg'),
  Listing(
      id: "5",
      state: "Active",
      name: "Black Jacket",
      postDate: "Tues, 18 Nov",
      requests: 9,
      likes: 6,
      views: 100,
      imgURL: 'assets/images/jacket.jpg'),
  Listing(
      id: "6",
      state: "Shared",
      name: "Black Jacket",
      postDate: "Tues, 18 Nov",
      requests: 9,
      likes: 6,
      views: 100,
      imgURL: 'assets/images/jacket.jpg'),
];
