// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsjyCRAEcqovauSIvm69iiRiaXfqRQWWc',
    appId: '1:882144857044:web:101b0ebdb6570e28eca441',
    messagingSenderId: '882144857044',
    projectId: 'cura-app-79f2f',
    authDomain: 'cura-app-79f2f.firebaseapp.com',
    storageBucket: 'cura-app-79f2f.appspot.com',
    measurementId: 'G-YD68SVLHLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAC-TckupksxQwJ8So9ORO42De33BwloU',
    appId: '1:882144857044:android:5840ffb16a06395beca441',
    messagingSenderId: '882144857044',
    projectId: 'cura-app-79f2f',
    storageBucket: 'cura-app-79f2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA6tU7dnF_sxgppUS9p2eYhnZOxBKpTmQ',
    appId: '1:882144857044:ios:2beae4ad36b02ea1eca441',
    messagingSenderId: '882144857044',
    projectId: 'cura-app-79f2f',
    storageBucket: 'cura-app-79f2f.appspot.com',
    iosClientId: '882144857044-e2ve3bf6q3eiiu1pg8usu0u9t8fuvd5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.curaFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA6tU7dnF_sxgppUS9p2eYhnZOxBKpTmQ',
    appId: '1:882144857044:ios:2beae4ad36b02ea1eca441',
    messagingSenderId: '882144857044',
    projectId: 'cura-app-79f2f',
    storageBucket: 'cura-app-79f2f.appspot.com',
    iosClientId: '882144857044-e2ve3bf6q3eiiu1pg8usu0u9t8fuvd5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.curaFrontend',
  );
}
